# MythosEngine/models/invite_code.py
"""
InviteCode model — a single-use token that allows a new user to self-register.

An admin generates an InviteCode and shares it out-of-band (Discord, email, etc.).
The recipient enters it in the SignupDialog to create their account.

Lifecycle:
  ACTIVE (unused)  →  REDEEMED (used_by set, use_count == max_uses)
                   →  EXPIRED  (expires_at in the past)
                   →  REVOKED  (is_active = False by admin)
"""

from datetime import datetime
from typing import Optional

from MythosEngine.models.base import CoreModel


class InviteCode(CoreModel):
    """A single-use invite token generated by an admin."""

    # Human-readable code shown to admin (e.g. "K3x9-mP2v-Jn4w")
    code: str

    # Who generated this invite
    created_by: str  # user_id of the admin

    # Who redeemed it (None = unused)
    used_by: Optional[str] = None

    # When the invite expires (default: 7 days from creation)
    expires_at: datetime

    # Maximum number of uses (always 1 for now, reserved for future)
    max_uses: int = 1

    # How many times it has been used
    use_count: int = 0

    # Set to False by admin to revoke before use
    is_active: bool = True

    # ── Computed state ────────────────────────────────────────────────────

    def is_valid(self) -> bool:
        """True only if this code can still be used right now."""
        return self.is_active and self.use_count < self.max_uses and datetime.utcnow() < self.expires_at

    @property
    def status(self) -> str:
        """Human-readable status string for the admin panel table."""
        if not self.is_active:
            return "Revoked"
        if self.use_count >= self.max_uses:
            return "Used"
        if datetime.utcnow() >= self.expires_at:
            return "Expired"
        return "Active"
